# Feature Encoding

Feature Encoding is the proccess of transforming `categorical features` into `numeric features`.Ths is necessary bcz ML algorithms can only handle numeric features such as:

- Label Encoding
- Ordinal Encoding
- One-hot Encoding
- Binary Encoding

In [2]:
# import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = sns.load_dataset('tips')
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
# value_counts of time
data['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

## 01-Label Encoding

In [28]:
# now encode the time column using label encoding
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder
le = LabelEncoder()

data['encoded_time'] = le.fit_transform(data['time'])
data.tail(20)

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
224,13.42,1.58,Male,Yes,Fri,Lunch,2,1,1.0
225,16.27,2.50,Female,Yes,Fri,Lunch,2,1,1.0
226,10.09,2.00,Female,Yes,Fri,Lunch,2,1,1.0
227,20.45,3.00,Male,No,Sat,Dinner,4,0,2.0
228,13.28,2.72,Male,No,Sat,Dinner,2,0,2.0
229,22.12,2.88,Female,Yes,Sat,Dinner,2,0,2.0
230,24.01,2.00,Male,Yes,Sat,Dinner,4,0,2.0
231,15.69,3.00,Male,Yes,Sat,Dinner,3,0,2.0
232,11.61,3.39,Male,No,Sat,Dinner,2,0,2.0
233,10.77,1.47,Male,No,Sat,Dinner,2,0,2.0
234,15.53,3.00,Male,Yes,Sat,Dinner,2,0,2.0
235,10.07,1.25,Male,No,Sat,Dinner,2,0,2.0
236,12.60,1.00,Male,Yes,Sat,Dinner,2,0,2.0
237,32.83,1.17,Male,Yes,Sat,Dinner,2,0,2.0
238,35.83,4.67,Female,No,Sat,Dinner,3,0,2.0
239,29.03,5.92,Male,No,Sat,Dinner,3,0,2.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0,2.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0,2.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0,2.0
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0.0

## 02-Ordinal Encoding

In [20]:
# check the day column value counts
data['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [26]:
# now encode the day column using ordinal encoding
oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
data['encoded_day']= oe.fit_transform(data[['day']])
data.tail()

,total_bill,tip,sex,smoker,day,time,size,encoded_time,encoded_day
239,29.03,5.92,Male,No,Sat,Dinner,3,0,2.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0,2.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0,2.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0,2.0
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0.0

## 03- One-Hot Encoding

In [34]:
ohe = OneHotEncoder()
ohe.fit_transform(data[['sex']]).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

## 04-Binary Encoding

In [ ]:
# before binary encoding, we need to install the category_encoders library.
!pip install category_encoders

In [41]:
# import catergory_encoders as ce
from category_encoders import BinaryEncoder
be = BinaryEncoder()

be.fit_transform(data[['smoker']])

     smoker_0  smoker_1
0           0         1
1           0         1
2           0         1
3           0         1
4           0         1
..        ...       ...
239         0         1
240         1         0
241         1         0
242         0         1
243         0         1

[244 rows x 2 columns]